# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\add.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDialog(object):
    def setupUi(self, AddDialog):
        AddDialog.setObjectName("AddDialog")
        AddDialog.resize(520, 591)
        self.excelPathLabel = QtWidgets.QLabel(AddDialog)
        self.excelPathLabel.setGeometry(QtCore.QRect(30, 40, 54, 12))
        self.excelPathLabel.setObjectName("excelPathLabel")
        self.excelPathLineEdit = QtWidgets.QLineEdit(AddDialog)
        self.excelPathLineEdit.setGeometry(QtCore.QRect(100, 30, 371, 20))
        self.excelPathLineEdit.setPlaceholderText("")
        self.excelPathLineEdit.setObjectName("excelPathLineEdit")
        self.exportPathLabel = QtWidgets.QLabel(AddDialog)
        self.exportPathLabel.setGeometry(QtCore.QRect(30, 120, 54, 12))
        self.exportPathLabel.setObjectName("exportPathLabel")
        self.exportPathLineEdit = QtWidgets.QLineEdit(AddDialog)
        self.exportPathLineEdit.setGeometry(QtCore.QRect(100, 110, 371, 20))
        self.exportPathLineEdit.setObjectName("exportPathLineEdit")
        self.sumExportLabel = QtWidgets.QLabel(AddDialog)
        self.sumExportLabel.setGeometry(QtCore.QRect(30, 190, 54, 12))
        self.sumExportLabel.setObjectName("sumExportLabel")
        self.addPushButton = QtWidgets.QPushButton(AddDialog)
        self.addPushButton.setGeometry(QtCore.QRect(430, 550, 75, 23))
        self.addPushButton.setObjectName("addPushButton")
        self.exitPushButton = QtWidgets.QPushButton(AddDialog)
        self.exitPushButton.setGeometry(QtCore.QRect(330, 550, 75, 23))
        self.exitPushButton.setObjectName("exitPushButton")
        self.parentsListWidget = QtWidgets.QListWidget(AddDialog)
        self.parentsListWidget.setGeometry(QtCore.QRect(100, 210, 221, 311))
        self.parentsListWidget.setObjectName("parentsListWidget")
        self.selectedParentLabel = QtWidgets.QLabel(AddDialog)
        self.selectedParentLabel.setGeometry(QtCore.QRect(100, 180, 371, 21))
        self.selectedParentLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.selectedParentLabel.setText("")
        self.selectedParentLabel.setTextFormat(QtCore.Qt.AutoText)
        self.selectedParentLabel.setWordWrap(True)
        self.selectedParentLabel.setObjectName("selectedParentLabel")
        self.exportSheetLineEdit = QtWidgets.QLineEdit(AddDialog)
        self.exportSheetLineEdit.setGeometry(QtCore.QRect(100, 70, 371, 20))
        self.exportSheetLineEdit.setObjectName("exportSheetLineEdit")
        self.exportSheetLabel = QtWidgets.QLabel(AddDialog)
        self.exportSheetLabel.setGeometry(QtCore.QRect(30, 80, 54, 12))
        self.exportSheetLabel.setObjectName("exportSheetLabel")
        self.exportEncryptLabel = QtWidgets.QLabel(AddDialog)
        self.exportEncryptLabel.setGeometry(QtCore.QRect(30, 160, 54, 12))
        self.exportEncryptLabel.setObjectName("exportEncryptLabel")
        self.exportEncryptLineEdit = QtWidgets.QLineEdit(AddDialog)
        self.exportEncryptLineEdit.setGeometry(QtCore.QRect(100, 150, 371, 20))
        self.exportEncryptLineEdit.setObjectName("exportEncryptLineEdit")

        self.retranslateUi(AddDialog)
        QtCore.QMetaObject.connectSlotsByName(AddDialog)
        AddDialog.setTabOrder(self.excelPathLineEdit, self.exportSheetLineEdit)
        AddDialog.setTabOrder(self.exportSheetLineEdit, self.exportPathLineEdit)
        AddDialog.setTabOrder(self.exportPathLineEdit, self.parentsListWidget)
        AddDialog.setTabOrder(self.parentsListWidget, self.addPushButton)
        AddDialog.setTabOrder(self.addPushButton, self.exitPushButton)

    def retranslateUi(self, AddDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDialog.setWindowTitle(_translate("AddDialog", "新增"))
        self.excelPathLabel.setText(_translate("AddDialog", "文件路径"))
        self.exportPathLabel.setText(_translate("AddDialog", "导出路径"))
        self.sumExportLabel.setText(_translate("AddDialog", "合表"))
        self.addPushButton.setText(_translate("AddDialog", "确定"))
        self.exitPushButton.setText(_translate("AddDialog", "取消"))
        self.exportSheetLabel.setText(_translate("AddDialog", "sheet"))
        self.exportEncryptLabel.setText(_translate("AddDialog", "混淆路径"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddDialog = QtWidgets.QDialog()
    ui = Ui_AddDialog()
    ui.setupUi(AddDialog)
    AddDialog.show()
    sys.exit(app.exec_())
