# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(420, 492)
        self.mergedTableListWidget = QtWidgets.QListWidget(SettingDialog)
        self.mergedTableListWidget.setGeometry(QtCore.QRect(60, 60, 281, 371))
        self.mergedTableListWidget.setObjectName("mergedTableListWidget")
        self.exitButton = QtWidgets.QPushButton(SettingDialog)
        self.exitButton.setGeometry(QtCore.QRect(270, 460, 75, 23))
        self.exitButton.setObjectName("exitButton")
        self.addButton = QtWidgets.QPushButton(SettingDialog)
        self.addButton.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(SettingDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "合表管理"))
        self.exitButton.setText(_translate("SettingDialog", "确定"))
        self.addButton.setText(_translate("SettingDialog", "添加"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingDialog = QtWidgets.QDialog()
    ui = Ui_SettingDialog()
    ui.setupUi(SettingDialog)
    SettingDialog.show()
    sys.exit(app.exec_())
